# Generated by Django 6.0.2 on 2026-02-10 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='message',
        ),
    ]
