# Generated by Django 6.0.2 on 2026-02-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
