# Generated by Django 6.0.2 on 2026-02-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_photo_message_alter_photo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='message',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
    ]
