# Generated by Django 6.0.2 on 2026-02-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_remove_photo_message_remove_photo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
