# Generated by Django 6.0.2 on 2026-04-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_media_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='uploader_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
